version : '3.3'
services  :
#Container - 1 - website{node}
  docman_website:
    container_name: docman_website
    build: .
    links:
    - "docman-Text-extractor"
    - "elasticsearch"
    ports:
    - "3004:3004"
    environment:
      - TIKA_HOST=tika
      - TIKA_PORT=9998
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - NODE_PORT=3000
      - ELASTIC_URL=http://elasticsearch:9200 #may be incorrect     
    networks:
      - docnet      
#Container - 2  - Apacha Tikka + OCR
  docman-Text-extractor:
    container_name: Super-Text-extractor
    image : logicalspark/docker-tikaserver
    ports:
      - "9998:9998"
    networks:
      - docnet  
#Container - 3 - Database {Elastic Search}
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - Docman:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - docnet  
#Conatiner -4 Database Visualization Tool {kibana}
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - docnet  

volumes:
# For Conatiner 3 {elastic search}
  Docman:

networks:
  docnet:  
    driver: bridge    